// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlxxfiipaoovfqljdqcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRseHhmaWlwYW9vdmZxbGpkcWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjEyNjMsImV4cCI6MjA2NzQ5NzI2M30.T4AtBKynv8Dyj9Y3wFOS-qlZrEU6IKBfiDEfUsfnVPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});